### ISSUE TITLE
./run.sh: bad interpreter: /bin/bash^M: no such file or directory

### ISSUE THREAD

**Issue by bu2zhouzhu** [alexzaitsev/apk-dependency-graph#11]
My solution: Using sublime text open run.sh. View > Line Endings > Unix and save the file.

[reference](http://stackoverflow.com/questions/14219092/bash-my-script-bin-bashm-bad-interpreter-no-such-file-or-directory#answer-23202386)

**Comment by josinaldobarbosa** [comment]
It worked, but why is that?

**Comment by alexzaitsev** [comment]
That's because line endings were set to CRLF (Windows). I changed it to LF. It's already pushed and will be in the next release.

**Comment by alexzaitsev** [comment]
@bu2zhouzhu @josinaldobarbosa could you test current `run.sh` version? is it working?

**Comment by josinaldobarbosa** [comment]
worked, thank you.

**Comment by mateusgrb** [comment]
Facing this issue on a mac with the latest version(0.0.5). My solution was to open run.sh on vim and delete all ˆM occurrences.
