### ISSUE TITLE
Doesn't work with multidex

### ISSUE THREAD

**Issue by lucas34** [alexzaitsev/apk-dependency-graph#12]
Hi,

When the multidex is enable on big app, the tool with generate multiple smali files but the analyser will only read one folder.

Lucas

**Comment by alexzaitsev** [comment]
Is going to be fixed here https://github.com/alexzaitsev/apk-dependency-graph/pull/15

**Comment by alexzaitsev** [comment]
https://github.com/alexzaitsev/apk-dependency-graph/pull/15 is merged however i need to generate new jar and update it in the repository. You may build it from the source code by yourself if you do not want to wait :)

**Comment by alexzaitsev** [comment]
[new 0.1.0 release](https://github.com/alexzaitsev/apk-dependency-graph/releases/tag/0.1.0)
