### ISSUE TITLE
extentions feature

### ISSUE THREAD

**Issue by alexzaitsev** [alexzaitsev/apk-dependency-graph#19]
**Contributors wanted**
All of these changes touches mostly [src](https://github.com/alexzaitsev/apk-dependency-graph/tree/master/src/) module. To get better understanding of project structure please visit our [wiki pages](https://github.com/alexzaitsev/apk-dependency-graph/wiki).

**Why we need it?**
A lot of people are asking questions like "How can I filter Dagger dependecies?". I'm interested in generalizing of this idea to the concept of extensions (or plugins) - some piece of software, written by somebody, that you can join to your main program to boost it. (Important: it should not be recompiled.)

**How to do that?**
I have some ideas. In very simple realization extension can be a `json` file with settings. User can pass it to the [main program](https://github.com/alexzaitsev/apk-dependency-graph/blob/master/build/jar/apk-dependency-graph.jar) so we should add such ability also to the run scripts ([unix](https://github.com/alexzaitsev/apk-dependency-graph/blob/master/run.sh) and [windows](https://github.com/alexzaitsev/apk-dependency-graph/blob/master/run.bat)).
Another think - we should have ablitity to join multiple such files at a time. So [SmaliAnalyzer](https://github.com/alexzaitsev/apk-dependency-graph/blob/master/src/code/SmaliAnalyzer.java) will be provided by an array of rules and we should apply each rule one by one to outline the final set of classes which should be shown to the user. 

This is a very brief description, you can stick to some more adult solution 👍  If you have some additions - please leave them here. If you want to implement this I would love to aswer to all your questions! Thank you.

**Comment by kaygisiz** [comment]
Hi @alexzaitsev , i made a [plugin](https://plugins.jetbrains.com/plugin/10107-dependency-injection-graph) with inspired by your project. People who think about this issue can use this plugin and [contribute](https://github.com/kaygisiz/Dependency-Injection-Graph).

**Comment by alexzaitsev** [comment]
Thinking about it. WIP

**Comment by alexzaitsev** [comment]
Closed in favor of #48
