### ISSUE TITLE
Exception during "Copying original files...": "java.lang.StringIndexOutOfBoundsException: String index out of range"

### ISSUE THREAD

**Issue by jasonwyatt** [alexzaitsev/apk-dependency-graph#2]
Cool idea for a tool!

I just heard it and thought I'd give it a go with my app. I'm seeing a `StringIndexOutOfBoundsException` in the `Copying original files...` step.

```
/run.sh [path to android-debug.apk] [my package name]
I: Using Apktool 2.2.0 on android-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/jason/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -36
    at java.lang.String.substring(String.java:1955)
    at code.SmaliAnalyzer.parseAndAddClassNames(SmaliAnalyzer.java:150)
    at code.SmaliAnalyzer.parseAndAddClassNames(SmaliAnalyzer.java:151)
    at code.SmaliAnalyzer.processSmaliFile(SmaliAnalyzer.java:85)
    at code.SmaliAnalyzer.traverseSmaliCode(SmaliAnalyzer.java:58)
    at code.SmaliAnalyzer.traverseSmaliCode(SmaliAnalyzer.java:61)
    at code.SmaliAnalyzer.run(SmaliAnalyzer.java:32)
    at code.Main.main(Main.java:20)
```

Here's some more info about my environment:

```
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

OS X El Capitan 10.11.6
```

**Comment by alexzaitsev** [comment]
@jasonwyatt Hello and thank you for reporting an issue. 
Could you help me a little bit more? 
If yes - please clone the repository and add logging of current file name that is processing:
`private void processSmaliFile(File file) {`
So you'll able to see what file is problematic. 
After that please place the next log:
`System.out.println("line: " + line);`
before this line:
`String generic = line.substring(startGenericInLineIndex + 1, endGenericInLineIndex);`
and you'll know the problematic string in that file. 
Run the project (Eclipse is ok) and try to generate the graph again.
Please attach this problematic line here so i'll able to resolve the issue. 
Thank you.

**Comment by alexzaitsev** [comment]
Upd: I've added error handling. Please try to run v. 0.0.3: https://github.com/alexzaitsev/apk-dependency-graph/releases/tag/0.0.3
This is not a solution but a workaround.

**Comment by jasonwyatt** [comment]
I've tried the new version and I'm not seeing the stack trace anymore, now
it just asks me to check my filter.

```
I: Using Apktool 2.2.0 on android-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file:
```

/Users/jason/Library/apktool/framework/1.apk
    I: Regular manifest package...
    I: Decoding file-resources...
    I: Decoding values _/_ XMLs...
    I: Baksmaling classes.dex...
    I: Baksmaling classes2.dex...
    I: Copying assets and libs...
    I: Copying unknown files...
    I: Copying original files...
    Please check your filter!

**Comment by alexzaitsev** [comment]
Let me explain a bit how it works. Firstly it decompiles your apk to smali code using `apktool` jar. Then your smali code is analyzed by `apk-dependency-graph` jar. Please check your `android-debug/smali/` folder. Does the file structure corresponds to your code? If no - please make sure that you are not using Instant Run or some flavors that change your package during the build.

**Comment by jasonwyatt** [comment]
Cool, thanks for asking me to check the `smali` folder. It was pretty much empty for some reason. I re-built my apk and tried again.. now it's working.
