### ISSUE TITLE
Does anybody use Live Editor feature?

### ISSUE THREAD

**Issue by alexzaitsev** [alexzaitsev/apk-dependency-graph#23]
I'd like to know does anybody use it. I'm thinking about removing it and adding functionality of [extentions feature](https://github.com/alexzaitsev/apk-dependency-graph/issues/19) instead of it.  
Any feedback is appreciated.

**Comment by christopherperry** [comment]
I have not, although our team doesn't currently use this tool in our process. I'm trying to introduce this at least as part of our dashboard where we show bug counts.

**Comment by alexzaitsev** [comment]
Seems that this feature is unused.
