### ISSUE TITLE
Graph appears entirely blank

### ISSUE THREAD

**Issue by ryanzor** [alexzaitsev/apk-dependency-graph#24]
Hi, this tool looks neat, but I'm having some trouble with it.

I've gotten everything where it says it runs successfully, but the end result is an index.html page that has no dependency graph.  I've tried nofilter/filter by apk name and two separate apks.  The result always comes out the same.

Screenshot attached for clarity.

<img width="1429" alt="screen shot 2017-05-27 at 6 00 33 pm" src="https://cloud.githubusercontent.com/assets/1966657/26525249/aaac0b16-4306-11e7-95c6-d774e92bcebe.png">

I likely have something setup wrong, but I'm not sure what it is.

**Comment by alexzaitsev** [comment]
Hello @ryanzor, did you use apks with instant run enabled?
Also, please, check your gui/analyzed.js, is it empty?

**Comment by alexzaitsev** [comment]
Closing as inactive.

**Comment by Namiii** [comment]
Hello, I'm here because I'm facing the same issue, even built after disabling instant run and still nothing. Any idea on why this would happen?
