### ISSUE TITLE
Unable to access jarfile apk-dependency-graph.jar

### ISSUE THREAD

**Issue by shumin0809** [alexzaitsev/apk-dependency-graph#25]
Hi,

I tried to run your script but I got this error.
I don't find any apk-dependency-graph.jar in my folder. Can you please take a look on this issue?

Thanks,

**Comment by alexzaitsev** [comment]
Hello, @shumin0809 
Could you describe your steps in detail, provide screenshots etc?
I't impossible to help without information.
Thanks.

**Comment by shumin0809** [comment]
![screen shot 2017-06-13 at 1 08 09 pm](https://user-images.githubusercontent.com/5727209/27102270-742ccbda-5039-11e7-80a2-78ac91aa6650.png)
I've just followed your instructions. Clone the project and run the script on Mac terminal.

**Comment by alexzaitsev** [comment]
I see. Please, download [the latest release](https://github.com/alexzaitsev/apk-dependency-graph/releases/tag/0.1.2) and try it. It should work.  
The reason is that generated files were removed from the source. I fixed readme as well to avoid further confusion about the subject. 
Thanks.

**Comment by brandoFS** [comment]
@alexzaitsev I'm having the same issue now witht he latest version. Please Advise 

![image](https://user-images.githubusercontent.com/5471824/34794951-45e54bb8-f605-11e7-8114-ed89577464aa.png)

**Comment by matemink** [comment]
@brandoFS At first you should to compile build/jar/apk-dependency-graph.jar using ant, and then you get required build folder

**Comment by arenshaee** [comment]
@alexzaitsev  @shumin0809
check here:
https://github.com/alexzaitsev/apk-dependency-graph/issues/13#issuecomment-674503963
