### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Dkhusainov** [alexzaitsev/apk-dependency-graph#28]
Hello. Great tool, but performancy(in my case at leaast) is really bad.

I opened a generated graph of a Kotlin project(which means all the generated lamdas/inner classes) on my i7 and it was unusable.

Chrome version: 66.0.3359.170

Here's a short profile session from chrome

[lag.zip](https://github.com/alexzaitsev/apk-dependency-graph/files/2006177/lag.zip)

**Comment by alexzaitsev** [comment]
The situation should be improved when #49 is implemented. Also, please consider using filters (introduced in [0.2.0](https://github.com/alexzaitsev/apk-dependency-graph/releases/tag/0.2.0)).

**Comment by SupinePandora43** [comment]
lag)
![LAG](https://pp.userapi.com/c855220/v855220076/9bd10/3gdx42xbu0A.jpg)
YOU MUST USE FILTER!!!!!!
// [Project](https://github.com/SupinePandora43/Russian)

**Comment by alexzaitsev** [comment]
@SupinePandora43 I think I have to make filters & package-name option mandatory

**Comment by alexzaitsev** [comment]
@SupinePandora43 done at [0.2.1](https://github.com/alexzaitsev/apk-dependency-graph/releases/tag/0.2.1)

**Comment by alexzaitsev** [comment]
Html and js code re-factoring and cleanup is done in [0.3.0](https://github.com/alexzaitsev/apk-dependency-graph/releases/tag/0.3.0)
