### ISSUE TITLE
Can't get it to work, tried with multiple APKs

### ISSUE THREAD

**Issue by zoltanf** [alexzaitsev/apk-dependency-graph#35]
Tried with serveral different APKs. It builds and runs fine, but the analyzed.js is always:
```
var dependencies = {links:[
]};
```

I tried the current master as well as the dev branch, same results.
Tried with 2 different application APKs.

**Comment by victorrattis** [comment]
@zoltanf, Could you please send the command which you have used? 

**Obs.:** check if the APK package name is the same that you are using in this command.

**Comment by zoltanf** [comment]
Yes I double checked everything at the time. However the output in the js was alway empty. In the mean time I used the android studio plugin and it works fine. At the moment I can't provide you with more info.
