### ISSUE TITLE
Create scripts to publish the app for Windows, Linux and Mac

### ISSUE THREAD

**Issue by victorrattis** [alexzaitsev/apk-dependency-graph#40]
Create scripts to publish the app for Windows, Linux, and Mac.

The Objective of this issue is:
- Create a script to build the **apk-dependency-graph** jar and move it to "*gui/lib*" directory;
- Create scripts to package the electron app for Windows, Linux, and Mac platforms;
- Create scripts to creates the installers for Windows, Linux, and Max;
- Update the README.txt file with new information.

**Comment by alexzaitsev** [comment]
Love it!

**Comment by alexzaitsev** [comment]
Hey @victorrattis, how it's going? Would you have some spare time to finish it?

**Comment by victorrattis** [comment]
@alexzaitsev 
Let's go continue with work =)

The objective of this task is to create scripts to build and package the application for platforms Win, Mac, and Linux. I saw that this project is using Gradle to automate tasks (this is good). Would you like to use the Gradle tool to automate all tasks in this project?

If so, first we could remove the *ant* and use Gradle to build the jar then create the scripts/tasks using Gradle to build and package the app.

**Comment by victorrattis** [comment]
I am implementing this solution of using Gradle to build the jar and app to release it. You can see it (a draft) [here](https://github.com/victorrattis/apk-dependency-graph/commit/4f3e071c66ee3e1105e106a86e92419e723441c8)

**Comment by alexzaitsev** [comment]
yes, that's fine for me. Thank you @victorrattis !

**Comment by alexzaitsev** [comment]
Closing as obsolete.
