### ISSUE TITLE
Does not work for apk with enabled "Instant Run" feature

### ISSUE THREAD

**Issue by adjorno** [alexzaitsev/apk-dependency-graph#5]

**Comment by alexzaitsev** [comment]
Hello @adjorno 
`apktool` cannot decompile such builds. It's noted in the `readme`. So I'm closing this as not a valid bug.  
Moreover I think that a build with enabled `instant run` feature will contain a lot of 'rubbish' classes and need to be carefully filtered.

**Comment by adjorno** [comment]
In that case it would be useful to provide more informative message instead
of "check your filters!"

**Comment by alexzaitsev** [comment]
I'll try to handle this. Thank you for submitting the issue.

**Comment by alexzaitsev** [comment]
Fixed in 0.0.4
