### ISSUE TITLE
Migrate from Ant to Gradle

### ISSUE THREAD

**Issue by alexzaitsev** [alexzaitsev/apk-dependency-graph#59]

**Comment by SupinePandora43** [comment]
:tada:

**Comment by petemyron** [comment]
`gradle build` worked great for me. This can probably be closed.

**Comment by alexzaitsev** [comment]
@petemyron it works but `gradle` uses `ant` script. The goal is to rewrite it for gradle.

**Comment by alexzaitsev** [comment]
Done
