### ISSUE TITLE
Add Zoom-in (out) functionality

### ISSUE THREAD

**Issue by adjorno** [alexzaitsev/apk-dependency-graph#6]
It is impossible to use this tool for large projects because it creates unreadable graph: nodes are big, edges are small, adding class names just makes a mess. It would be great to have vector zooming to isolate some part of the graph which user is working with.

**Comment by alexzaitsev** [comment]
@adjorno first of all you can filter your application by the package name. That will greatly reduce a number of nodes on your graph. Secondly, you can skip inner classes (please check our readme) (this was added in 0.1.0 version, the feature is experimental so please don't hesitate to create issues). Thirdly, you can use some [live filtering](https://github.com/alexzaitsev/apk-dependency-graph/wiki/Live-filtering). Hope that this is enough to archieve your goal.
