### ISSUE TITLE
Is it possible to see dependencies by package?

### ISSUE THREAD

**Issue by ar-g** [alexzaitsev/apk-dependency-graph#63]
We wanted to use the dependency graph to easier untangle and understand dependencies in order to break down our monolithic project to separate feature modules. Out project contains more than 200 screens and the visualization is unusable and slow. 
Perhaps it would be more helpful to see dependencies by the package, is it possible?

**Comment by alexzaitsev** [comment]
@ar-g yes, that is possible. Please, refer to [filtering instructions](https://github.com/alexzaitsev/apk-dependency-graph/blob/master/filters/instructions.txt).

**Comment by SupinePandora43** [comment]
@alexzaitsev wow, you finally here! :D

**Comment by alexzaitsev** [comment]
@SupinePandora43 busy with other stuff :)
