### ISSUE TITLE
Add "exclude" filter

### ISSUE THREAD

**Issue by adjorno** [alexzaitsev/apk-dependency-graph#7]
Most of projects have utilities classes that don't need to be presented as dependencies. It would be great to have a possibility to exclude those classes from dependency graph.

**Comment by alexzaitsev** [comment]
It's implemented in 0.0.5 with `Live editor` feature. How-to: https://github.com/alexzaitsev/apk-dependency-graph/wiki

**Comment by adjorno** [comment]
Useless implementation

**Comment by alexzaitsev** [comment]
@adjorno could you explain your opinion?
