### ISSUE TITLE
No Permission? 

### ISSUE THREAD

**Issue by jp1017** [alexzaitsev/apk-dependency-graph#9]
:question: 

![2016-09-28 20-36-01](https://cloud.githubusercontent.com/assets/7868514/18913632/5065be62-85bb-11e6-8f43-b06c4265d224.png)

**Comment by jp1017** [comment]
This error shows on Ubuntu 16.04, and it's wonderful on Win10.

**Comment by alexzaitsev** [comment]
Please try `sudo chmod 777 ./run.sh`
